### PR TITLE
Added schedule schema and insert-match functionality

### PR DESCRIPTION
**Pull request by jeetdesai04**

### CODE REVIEW

**Comment by suthar26** [comment]
Thoughts on putting the populate schedule as part of a protected route so the admin/super-scout can invoke the script through that end point. Removes the need for running a script from a computer.

**Comment by suthar26** [comment]
Thoughts on putting the populate schedule as part of a protected route so the admin/super-scout can invoke the script through that end point. Removes the need for running a script from a computer.

**Review by suthar26 — APPROVED** [review]
Lgtm

**Comment by jeetdesai04** [comment]
I'm down to go with your suggestion on the protected route solution, let's keep this the way as is to at least have something for the frontend to work with.

**Pull request merged**
